"""added up_date column

Revision ID: 28e997a072f8
Revises: 7e00ae48ac99
Create Date: 2018-02-12 21:40:53.655315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e997a072f8'
down_revision = '7e00ae48ac99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('up_date', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
        batch_op.drop_column('up_date')
    # ### end Alembic commands ###
